const traitMatrix = {
    "Cuts Inside From Both Wings": {
        "Cuts Inside From Both Wings": 1, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One- Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 1, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Knocks Ball Past Opponent": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 1, "Runs With Ball Rarely": 1, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Runs With Ball Rarely": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 1, "Runs With Ball Rarely": 1, "Runs With Ball Often": 1, "Runs With Ball Down Left": 1, "Runs With Ball Down Right": 1, "Runs With Ball Through Centre": 1, "Brings Ball Out Of Defense": 1, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 1, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 1
    },
    "Runs With Ball Often": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 1, "Runs With Ball Often": 1, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Runs With Ball Down Left": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 1, "Runs With Ball Often": 0, "Runs With Ball Down Left": 1, "Runs With Ball Down Right": 1, "Runs With Ball Through Centre": 1, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Runs With Ball Down Right": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 1, "Runs With Ball Often": 0, "Runs With Ball Down Left": 1, "Runs With Ball Down Right": 1, "Runs With Ball Through Centre": 1, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Runs With Ball Through Centre": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 1, "Runs With Ball Often": 0, "Runs With Ball Down Left": 1, "Runs With Ball Down Right": 1, "Runs With Ball Through Centre": 1, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Brings Ball Out Of Defense": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 1, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 1, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Stops Play": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 1, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Arrives Late In Opponent's Area": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 1, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 1, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 1, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Comes Deep To Get Ball": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 1, "Gets Forward Whenever Possible": 1, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 1, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Gets Forward Whenever Possible": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 1, "Gets Forward Whenever Possible": 1, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 1, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Gets Into Opposition Area": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 1, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 1, "Hugs Line": 1, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 1, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Hugs Line": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 1, "Hugs Line": 1, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Likes To Try To Beat Offside Trap": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 1, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 1, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 1, "Does Not Move Into Channels": 1, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Moves Into Channels": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 1, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 1, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 1, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Plays One-Twos": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 1, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Plays With Back To Goal": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 1, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 1, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Does Not Move Into Channels": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 1, "Moves Into Channels": 1, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 1, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Likes Ball Played To Feet": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 1, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Stays Back At All Times": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 1, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 1, "Gets Into Opposition Area": 1, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 1, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 1, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Dictates Tempo": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 1, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Likes To Switch Ball To Other Flank": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 1, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 1, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Looks For Pass Rather Than Attempting To Score": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 1, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 1, "Shoots With Power": 0, "Tries First Time Shots": 1, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Plays No Through Balls": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 1, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 1, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Plays Short Simple Passes": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 1, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 1, "Tries Killer Balls Often": 1, "Crosses Early": 0, "Tries Long Range Passes": 1, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Tries Killer Balls Often": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 1, "Plays Short Simple Passes": 1, "Tries Killer Balls Often": 1, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Crosses Early": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 1, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Tries Long Range Passes": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 1, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 1, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Attempts Overhead Kicks": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 1, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Hits Free Kicks With Power": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 1, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 1, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Likes To Lob Keeper": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 1, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Likes To Round Keeper": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 1, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 1, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Places Shots": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 1, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 1, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Refrains From Taking Long Shots": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 1, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 1, "Shoots From Distance": 1, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 1, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Shoots From Distance": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 1, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Shoots With Power": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 1, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 1, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Tries First Time Shots": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 1, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 1, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Tries Long Range Free Kicks": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 1, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 1, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Argues With Officials": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 1, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Winds Up Opponents": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 1, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Gets Crowd Going": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 1, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Dives Into Tackles": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 1, "Does Not Dive Into Tackles": 1, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Does Not Dive Into Tackles": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 1, "Does Not Dive Into Tackles": 1, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Marks Opponent Tightly": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 1, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Avoids Using Weaker Foot": {
        "Cuts Inside From Both Wings": 1, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 1, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Curls Ball": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 1, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Tries Tricks": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 1, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Likes To Beat Opponent Repeatedly": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 1, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Uses Outside Of Foot": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 1, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 0
    },
    "Possess Long Flat Throw": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 0, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 1, "Tries To Play Way Out Of Trouble": 0
    },
    "Tries To Play Way Out Of Trouble": {
        "Cuts Inside From Both Wings": 0, "Knocks Ball Past Opponent": 0, "Runs With Ball Rarely": 1, "Runs With Ball Often": 0, "Runs With Ball Down Left": 0, "Runs With Ball Down Right": 0, "Runs With Ball Through Centre": 0, "Brings Ball Out Of Defense": 0, "Stops Play": 0, "Arrives Late In Opponent's Area": 0, "Comes Deep To Get Ball": 0, "Gets Forward Whenever Possible": 0, "Gets Into Opposition Area": 0, "Hugs Line": 0, "Likes To Try To Beat Offside Trap": 0, "Moves Into Channels": 0, "Plays One - Twos": 0, "Plays With Back To Goal": 0, "Does Not Move Into Channels": 0, "Likes Ball Played To Feet": 0, "Stays Back At All Times": 0, "Dictates Tempo": 0, "Likes To Switch Ball To Other Flank": 0, "Looks For Pass Rather Than Attempting To Score": 0, "Plays No Through Balls": 0, "Plays Short Simple Passes": 0, "Tries Killer Balls Often": 0, "Crosses Early": 0, "Tries Long Range Passes": 0, "Attempts Overhead Kicks": 0, "Hits Free Kicks With Power": 0, "Likes To Lob Keeper": 0, "Likes To Round Keeper": 0, "Places Shots": 0, "Refrains From Taking Long Shots": 0, "Shoots From Distance": 0, "Shoots With Power": 0, "Tries First Time Shots": 0, "Tries Long Range Free Kicks": 0, "Argues With Officials": 0, "Winds Up Opponents": 0, "Gets Crowd Going": 0, "Dives Into Tackles": 0, "Does Not Dive Into Tackles": 0, "Marks Opponent Tightly": 0, "Avoids Using Weaker Foot": 0, "Curls Ball": 0, "Tries Tricks": 0, "Likes To Beat Opponent Repeatedly": 0, "Uses Outside Of Foot": 0, "Possess Long Flat Throw": 0, "Tries To Play Way Out Of Trouble": 1
    }
}


// Fetches the build of the player whose user is logged in
async function fetchPlayer() {
    const url = "https://api.simulationsoccer.com/ssl/getPlayer?username=" + username

    const playerData = fetch(url)

    playerData
        .then((response) => response.json())
        .then((data) => {
            // data contains in its [0] index, the javascript object with all information
            document.querySelector("#playerName").innerText = data[0].Name

            const url = "https://api.simulationsoccer.com/ssl/getBankBalance?user=" + username

            const bankData = fetch(url)

            bankData
                .then((response) => response.json())
                .then((data) => {

                    let number = parseFloat(data[0].Balance)

                    document.querySelector("#playerBank").innerText = number.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
                })

            const traitOption = document.querySelector("#removeTrait1")

            const ownedTraits = data[0]['All Traits'].split(" \\ ")

            const allTraits = document.querySelectorAll("select[id^='trait'] option")

            for (const trait in ownedTraits) {
                // console.log(ownedTraits[trait])
                const option = document.createElement("option");
                option.text = ownedTraits[trait];
                option.value = "500000";
                traitOption.appendChild(option)

                if (traitMatrix[trait] != undefined) {
                    const conflictTraits = traitMatrix[trait]

                    allTraits.forEach(element => {
                        var name = element.innerText

                        // console.log(name)

                        if (name == "Select a trait") {
                            // DO NOTHING
                        } else {
                            if (conflictTraits[name] == 1) {
                                element.disabled = true
                                // console.log("YES")
                            } else {
                                element.disabled = false
                            }
                        }
                    });
                } else {
                    console.log("Your trait is misspelled.")
                }
            }


        });
}


function updateCost(element) {
    var cost = document.querySelector('#' + element.id + 'Cost')

    cost.innerText = element.value
}


// Function to gather the information from the form
function updateOutput() {
    const purchases = document.querySelectorAll("div[class$='Purchase'] table")

    const url = "https://api.simulationsoccer.com/ssl/getPlayer?username=" + username

    const playerData = fetch(url)

    playerData
        .then((response) => response.json())
        .then((data) => {
            const baseString = `${data[0].Name} - ${username} - ${data[0].Team}`

            let purchaseString = ""

            purchases.forEach(element => {

                // console.log(element)
                const items = element.querySelectorAll("select")

                items.forEach(element => {
                    let selectedIndex = element.selectedIndex;

                    // Only writes if a purchase has been made.
                    if (selectedIndex != 0) {
                        purchaseString += `${baseString} - -${element.options[selectedIndex].value} - ${element.options[selectedIndex].innerText}\n`
                    }
                });
            });

            Swal.fire({
                title: "Purchase Summarized!",
                html: '<pre>' + purchaseString + '</pre> ',
                icon: 'success',
                confirmButtonText: 'Copy text'
            }).then(function (isConfirm) {
                if (isConfirm) {
                    // Copy the text inside the text field
                    navigator.clipboard.writeText(purchaseString);
                } else {
                    // DO NOTHING
                }
            })
        })

    return false;
}

function submitCheck() {
    const balanceCurrency = document.querySelector("#playerBank").innerHTML

    const balanceNumber = balanceCurrency.replace(/[^\d.-]/g, '');

    const balance = parseFloat(balanceNumber)

    const costs = document.querySelectorAll("span[id$='Cost']")

    var sum = 0

    costs.forEach(element => {
        sum += parseInt(element.innerHTML)
    });

    // console.log(balance)
    // console.log(sum)
    // console.log(balance - sum)

    if (balance - sum < 0) {

        Swal.fire({
            title: 'Too much money spent!',
            text: 'You have spent more money on your purchase than you have in your bank.',
            icon: 'error',
            confirmButtonText: 'OK'
        })
    } else {
        console.log("Checked and summarizing")

        updateOutput()
    }
}

function addRow(element) {
    const table = element.parentNode.parentNode.querySelector("table[id$='Table']")

    var numRows = getRowsInUpdateTable(table);

    var newRow = table.rows[1].cloneNode(true)

    newRow.querySelector("td").innerHTML = numRows

    var ids = newRow.querySelectorAll('[id*="1"]')

    for (var i = 0; i < ids.length; i++) {
        var oldId = ids[i].getAttribute('id');
        var newId = oldId.replace(/1/g, numRows);
        ids[i].setAttribute('id', newId);
    }

    table.append(newRow)

}

function removeRow(element) {
    const table = element.parentNode.parentNode.querySelector("table[id$='Table']")

    var numRows = getRowsInUpdateTable(table);

    if (numRows <= 2) {
        return;
    } else {
        table.deleteRow(-1)
    }

}

function getRowsInUpdateTable(element) {
    return document.querySelectorAll('#' + element.id + ' tr').length;
}